In [ ]:
#DEEP NEURAL

In [62]:
import os
import pandas as pd

In [63]:
import os
import numpy as np
import pandas as pd

In [64]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [65]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [66]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from keras import optimizers

In [67]:
from sklearn import model_selection
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [68]:
seed = 7
np.random.seed(seed)

In [69]:
dataframe = pd.read_csv("C:/Users/User/Desktop/DOUTORADO/Phyton/Projeto Final - AVALIATIVO/PARTE BEL/matches.csv")

In [74]:
dataframe

year  match_number        team_a  goals_team_a  goals_team_b  \
0    1991             1      China PR             4             0   
1    1991            23        Sweden             1             4   
2    1991            13      China PR             4             1   
3    1991             2       Denmark             3             0   
4    1991             8        Norway             4             0   
..    ...           ...           ...           ...           ...   
240  2019            27  South Africa             0             4   
241  2019            29       Jamaica             1             4   
242  2019            33   Netherlands             2             1   
243  2019            42        Sweden             1             0   
244  2019            44   Netherlands             2             1   

          team_b  score_diff winner  matches_played_a  matches_won_a  ...  \
0         Norway           4      a                 3              2  ...   
1         Norway          -3      b                 6              4  ...   
2    New Zealand           3      a                 3              2  ...   
3    New Zealand           3      a                 3              1  ...   
4    New Zealand           4      a                 6              4  ...   
..           ...         ...    ...               ...            ...  ...   
240      Germany          -4      b                 3              0  ...   
241    Australia          -3      b                 3              0  ...   
242       Canada           1      a                 7              6  ...   
243       Canada           1      a                 7              5  ...   
244        Japan           1      a                 7              6  ...   

     podium_score_cum_a  matches_won_cum_percent_a  matches_played_b  \
0                     0                  66.666667                 6   
1                     4                  66.666667                 6   
2                     0                  66.666667                 3   
3                     0                  33.333333                 3   
4                     8                  66.666667                 3   
..                  ...                        ...               ...   
240                   0                   0.000000                 5   
241                   0                   0.000000                 3   
242                   8                  70.000000                 4   
243                  20                  65.714286                 4   
244                   8                  70.000000                 3   

     matches_won_b  podium_score_b  cups_won_b  matches_played_cum_b  \
0                4               8           0                     6   
1                4               8           0                     6   
2                0               0           0                     3   
3                0               0           0                     3   
4                0               0           0                     3   
..             ...             ...         ...                   ...   
240              4               0           2                    39   
241              2               0           0                    20   
242              2               0           0                    22   
243              2               0           0                    22   
244              1               0           1                    29   

     matches_won_cum_b  podium_score_cum_b  matches_won_cum_percent_b  
0                    4                   8                  66.666667  
1                    4                   8                  66.666667  
2                    0                   0                   0.000000  
3                    0                   0                   0.000000  
4                    0                   0                   0.000000  
..                 ...                 ...                        ...  
240              

In [119]:
dataframe_dp = dataframe[["year","matches_won_cum_percent_a","podium_score_cum_a","matches_won_cum_percent_b","podium_score_cum_b","winner"]]

In [120]:
dataframe_dp

year  matches_won_cum_percent_a  podium_score_cum_a  \
0    1991                  66.666667                   0   
1    1991                  66.666667                   4   
2    1991                  66.666667                   0   
3    1991                  33.333333                   0   
4    1991                  66.666667                   8   
..    ...                        ...                 ...   
240  2019                   0.000000                   0   
241  2019                   0.000000                   0   
242  2019                  70.000000                   8   
243  2019                  65.714286                  20   
244  2019                  70.000000                   8   

     matches_won_cum_percent_b  podium_score_cum_b winner  
0                    66.666667                   8      a  
1                    66.666667                   8      b  
2                     0.000000                   0      a  
3                     0.000000                   0      a  
4                     0.000000                   0      a  
..                         ...                 ...    ...  
240                  76.923077                  44      b  
241                  35.000000                   0      b  
242                  36.363636                   2      a  
243                  36.363636                   2      a  
244                  48.275862                  24      a  

[245 rows x 6 columns]

In [121]:
dataset = dataframe_dp.values

In [122]:
dataset

array([[1991, 66.66666666666666, 0, 66.66666666666666, 8, 'a'],
       [1991, 66.66666666666666, 4, 66.66666666666666, 8, 'b'],
       [1991, 66.66666666666666, 0, 0.0, 0, 'a'],
       ...,
       [2019, 70.0, 8, 36.36363636363637, 2, 'a'],
       [2019, 65.71428571428571, 20, 36.36363636363637, 2, 'a'],
       [2019, 70.0, 8, 48.27586206896552, 24, 'a']], dtype=object)

In [123]:
X = dataset[:,0:5].astype(np.float32)
Y = dataset[:,5]

In [124]:
X

array([[1.9910000e+03, 6.6666664e+01, 0.0000000e+00, 6.6666664e+01,
        8.0000000e+00],
       [1.9910000e+03, 6.6666664e+01, 4.0000000e+00, 6.6666664e+01,
        8.0000000e+00],
       [1.9910000e+03, 6.6666664e+01, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       ...,
       [2.0190000e+03, 7.0000000e+01, 8.0000000e+00, 3.6363636e+01,
        2.0000000e+00],
       [2.0190000e+03, 6.5714287e+01, 2.0000000e+01, 3.6363636e+01,
        2.0000000e+00],
       [2.0190000e+03, 7.0000000e+01, 8.0000000e+00, 4.8275864e+01,
        2.4000000e+01]], dtype=float32)

In [125]:
Y

array(['a', 'b', 'a', 'a', 'a', 'b', 'b', 'b', 'a', 'a', 'a', 'b', 'b',
       'b', 'b', 'b', 'b', 'a', 'b', 'b', 'b', 'b', 'a', 'a', 'a', 'a',
       'a', 'b', 'a', 'a', 'b', 'a', 'b', 'b', 'b', 'a', 'b', 'a', 'a',
       'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'a', 'a', 'a', 'a',
       'a', 'b', 'a', 'a', 'a', 'a', 'a', 'a', 'b', 'a', 'a', 'b', 'b',
       'a', 'a', 'a', 'a', 'b', 'b', 'a', 'a', 'b', 'a', 'b', 'b', 'a',
       'a', 'a', 'b', 'a', 'a', 'a', 'a', 'b', 'a', 'b', 'a', 'a', 'b',
       'a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'a', 'a', 'a', 'a', 'b',
       'a', 'a', 'a', 'b', 'a', 'a', 'a', 'b', 'b', 'b', 'a', 'a', 'a',
       'a', 'a', 'a', 'b', 'b', 'b', 'a', 'a', 'a', 'a', 'a', 'b', 'a',
       'b', 'b', 'a', 'a', 'a', 'b', 'b', 'a', 'a', 'a', 'a', 'b', 'b',
       'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'a', 'b',
       'a', 'a', 'a', 'b', 'a', 'a', 'a', 'b', 'b', 'b', 'a', 'a', 'a',
       'a', 'a', 'a', 'a', 'b', 'a', 'b', 'a', 'a', 'b', 'a', 'b

In [126]:
encoder = LabelEncoder()
encoder.fit(Y)
Y = encoder.transform(Y)

In [127]:
Y

array([0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0])

In [283]:
def create_baseline():
    # Criar Modelo
    model = Sequential()
    model.add(Dense(10, input_dim=5, kernel_initializer='normal', activation='relu')) 
    model.add(Dense(8, kernel_initializer='normal', activation='relu'))
    model.add(Dense(6, kernel_initializer='normal', activation='relu'))
    model.add(Dense(4, kernel_initializer='normal', activation='relu'))
    model.add(Dense(1, kernel_initializer='normal', activation='sigmoid')) 
    # Compilar Modelo
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) 
    return model

In [284]:
create_baseline()

In [285]:
estimator = KerasClassifier(build_fn=create_baseline, nb_epoch=100, batch_size=5, verbose=1)

C:\Users\User\AppData\Local\Temp/ipykernel_7504/1484600318.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  estimator = KerasClassifier(build_fn=create_baseline, nb_epoch=100, batch_size=5, verbose=1)


In [286]:
estimator

In [287]:
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X, Y, cv=kfold)
print("Results: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

5/5 [==============================] - 0s 2ms/step - loss: 0.6906 - accuracy: 0.6250
Results: 62.45% (1.39%)


In [288]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.20)

In [289]:
estimator.fit(X_train, Y_train)

40/40 [==============================] - 0s 2ms/step - loss: 0.6888 - accuracy: 0.6020


In [290]:
predictions = estimator.predict(X_test)
print(predictions)

2/2 [==============================] - 0s 3ms/step
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [291]:
encoder = LabelEncoder()
encoder.fit(Y)
Y = encoder.transform(Y)

In [292]:
Y

array([0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0], dtype=int64)

In [293]:
predictions_encoded = encoder.inverse_transform(predictions)
print(predictions_encoded)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0]


C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [296]:
print(accuracy_score(Y_test, predictions))

0.7142857142857143


In [299]:
probs = estimator.predict_proba(X_test)
print(probs)

2/2 [==============================] - 0s 3ms/step
[[0.5281906  0.47180942]
 [0.5277804  0.4722196 ]
 [0.52836347 0.4716365 ]
 [0.52841175 0.47158828]
 [0.52800345 0.47199655]
 [0.52759594 0.47240406]
 [0.527594   0.472406  ]
 [0.5268338  0.4731662 ]
 [0.52809566 0.47190434]
 [0.5269864  0.47301358]
 [0.5277283  0.47227165]
 [0.5278466  0.47215346]
 [0.5284152  0.47158477]
 [0.52733946 0.4726605 ]
 [0.52800345 0.47199655]
 [0.5285387  0.47146127]
 [0.5277992  0.4722008 ]
 [0.52712214 0.4728779 ]
 [0.52741206 0.4725879 ]
 [0.5272252  0.4727748 ]
 [0.5270955  0.4729045 ]
 [0.5276438  0.47235623]
 [0.52809596 0.471904  ]
 [0.52822495 0.47177505]
 [0.5275787  0.47242126]
 [0.52786624 0.47213376]
 [0.5272262  0.47277376]
 [0.52787083 0.47212917]
 [0.5280203  0.47197968]
 [0.52803445 0.47196555]
 [0.52827895 0.47172102]
 [0.528088   0.47191206]
 [0.52730024 0.47269976]
 [0.5280426  0.4719574 ]
 [0.52843976 0.47156027]
 [0.528327   0.47167298]
 [0.528252   0.471748  ]
 [0.5278642  0.47213575]